---
    - name: Filesystem extend
      hosts: all
      become: true
      tasks:
      - include_vars:
          file: filesystemextendvar.yaml
      - name: Get Filesystem Size
        shell: echo {{extend_size}}
        register: extend_size
      - name: Get existing Filesystem size
        shell: df -h |grep {{filesystemname}} | awk '{print $4}' | sed "s/[G\"]//g"
        register: existing_filesize
      - name: Print existing filesize
        debug:
          var: existing_filesize
      - name: Print get filesize
        debug:
          var: extend_size
      - name : Final Lv Size
        set_fact:
          tmp_size_k: "{{ (extend_size.stdout | int) + (existing_filesize.stdout | int) }}"
      - name: Print totalsize
        debug:
          var: tmp_size_k
      - name: Appending G in LV size
        shell: echo {{tmp_size_k}} | sed '/:[0-9]*$/ ! s/$/g/'
        register: totalsizeg
      - name: Print totalsize with g
        debug:
          var: totalsizeg
      - name: Get Volumegroup details
        shell: lsblk |grep {{filesystemname}} |awk 'FNR==1'|sed 's/--/+/g'|awk -F "-" '{print $1}'|sed -r 's/^.{2}//'|sed 's/+/-/g'
        register: vg_name
      - name: Print VgOutput
        debug:
          var: vg_name
      - name: Get PV details
        shell: pvs | grep -w "{{vg_name.stdout}}" | awk '{print $1}' | xargs -n10 |sed -e 's/\s\+/,/g'
        register: exisiting_pv
      - name: Print Existing PV name
        debug:
          var: exisiting_pv
      - name: Get Logicalvolume details
        shell: lsblk |grep {{filesystemname}} |awk 'FNR==1'|sed 's/--/+/g'|awk -F "-" '{print $2}'|sed 's/+/-/g'|awk -F " " '{print $1}'
        register: lv_name
      - name: Print LV name
        debug:
          var: lv_name
      - name: pv add for volume group
        lvg:
          vg: "{{vg_name.stdout}}"
          pvs: "{{exisiting_pv.stdout}},{{new_pvs}}"
      - name: Extend the logical volume
        lvol:
          vg: "{{vg_name.stdout}}"
          lv: "{{lv_name.stdout}}"
          size: "{{totalsizeg.stdout}}"
          resizefs: true
          force: yes